In [1]:
import pandas as pd

In [2]:
campaign_data = pd.read_csv("D:/MP1/MP.csv")

In [3]:
campaign_data.head(7)

,Campaign_ID,Product_ID,Budget,Clicks,Conversions,Revenue_Generated,ROI,Customer_ID,Subscription_Tier,Subscription_Length,Flash_Sale_ID,Discount_Level,Units_Sold,Bundle_ID,Bundle_Price,Customer_Satisfaction_Post_Refund,Common_Keywords
0,CMP_RLSDVN,PROD_HBJFA3,41770.45,4946,73,15520.09,1.94,CUST_1K7G39,Premium,4,FLASH_1VFK5K,43,34,BNDL_29U6W5,433.80,4,Affordable
1,CMP_JHHUE9,PROD_OE8YNJ,29900.93,570,510,30866.17,0.76,CUST_0DWS6F,Premium,4,FLASH_1M6COK,28,97,BNDL_ULV60J,289.29,2,Innovative
2,CMP_6SBOWN,PROD_4V8A08,22367.45,3546,265,32585.62,1.41,CUST_BR2GST,Basic,9,FLASH_J4PEON,51,160,BNDL_0HY0EF,462.87,4,Affordable
3,CMP_Q31QCU,PROD_A1Q6ZB,29957.54,2573,781,95740.12,3.32,CUST_6TBY6K,Premium,32,FLASH_1TOVXT,36,159,BNDL_AI09BC,334.16,1,Durable
4,CMP_AY0UTJ,PROD_F57N66,36277.19,818,79,81990.43,3.53,CUST_XASI45,Standard,29,FLASH_AOBHXL,20,52,BNDL_R03ITT,371.67,2,Affordable
5,CMP_5F4E9W,PROD_2CF719,41159.74,1259,763,65792.30,0.77,CUST_GH04I5,Basic,31,FLASH_9E2DOQ,17,88,BNDL_2AM8LH,194.93,2,Affordable
6,CMP_WDWHH6,PROD_QN8SL7,32787.71,3882,29,54205.71,4.84,CUST_TRQ4H8,Basic,9,FLASH_LS82UL,44,75,BNDL_XBACO2,232.09,1,Stylish

In [4]:
campaign_data.dtypes

Campaign_ID                           object
Product_ID                            object
Budget                               float64
Clicks                                 int64
Conversions                            int64
Revenue_Generated                    float64
ROI                                  float64
Customer_ID                           object
Subscription_Tier                     object
Subscription_Length                    int64
Flash_Sale_ID                         object
Discount_Level                         int64
Units_Sold                             int64
Bundle_ID                             object
Bundle_Price                         float64
Customer_Satisfaction_Post_Refund      int64
Common_Keywords                       object
dtype: object

In [5]:
# Primo report con calcolo dei KPIs mancanti per avere un quandro più preciso sui risultati delle campagne da monitorare
campaign_report = (campaign_data
                   .assign(
                       ARPU = lambda x: (x['Revenue_Generated']/x['Conversions']),
                       Cost_per_Click = lambda x: (x['Budget']/x['Clicks']),
                       ROAS = lambda x: (x['Revenue_Generated']/x['Budget']),
                       Profit_Margin = campaign_data['Revenue_Generated'] - campaign_data['Budget']
                   )
                   .groupby(['Campaign_ID','Subscription_Tier'])
                   .agg(
                       Profit_Margin = ('Profit_Margin','sum'),
                       ROAS = ('ROAS','mean'),
                       ARPU = ('ARPU','mean'),
                       Cost_per_Click = ('Cost_per_Click','mean'),
                       Units_Sold = ('Units_Sold','sum'),
                       Total_Cost = ('Budget','sum'),
                       Total_Conversions = ('Conversions','sum'),
                       Avg_Discount_Level = ('Discount_Level','mean'),
                       ROI = ('ROI','sum'),
                       Subscription_Length = ('Subscription_Length','sum')
                   )
                   .round(0)
                   .reset_index()
)

In [6]:
campaign_report.head(5)

,Campaign_ID,Subscription_Tier,Profit_Margin,ROAS,ARPU,Cost_per_Click,Units_Sold,Total_Cost,Total_Conversions,Avg_Discount_Level,ROI,Subscription_Length
0,CMP_005HPN,Standard,49389.0,2.0,150.0,44.0,20,33263.0,552,59.0,3.0,23
1,CMP_009N8Q,Basic,27702.0,2.0,117.0,66.0,52,40292.0,582,17.0,3.0,6
2,CMP_00ASCH,Standard,53142.0,2.0,149.0,11.0,41,42099.0,640,66.0,2.0,32
3,CMP_00QX5K,Premium,35052.0,2.0,157.0,13.0,4,49462.0,539,40.0,2.0,24
4,CMP_00T86Z,Premium,6939.0,1.0,175.0,18.0,41,32359.0,225,64.0,4.0,17

In [7]:
# Raggruppamento con calcolo di valori massimi, medi, minimi per poter satbilire dei range e attuare classificazioni
data_overview = (campaign_report.groupby('Subscription_Tier')
                               .agg(
                                Max_sales = ('Units_Sold','max'),
                                Avg_sales = ('Units_Sold','mean'),
                                Min_sales = ('Units_Sold','min'),
                                Max_Conversions = ('Total_Conversions','max'),
                                Avg_Conversions = ('Total_Conversions','mean'),
                                Min_Conversions = ('Total_Conversions','min'),
                                Max_arpu = ('ARPU','max'),
                                Mean_arpu = ('ARPU','mean'),
                                Min_arpu = ('ARPU','min'),
                                Max_CPC = ('Cost_per_Click','max'),
                                Mean_CPC = ('Cost_per_Click','mean'),
                                Min_CPC = ('Cost_per_Click','min'),
                                max_roas = ('ROAS','max'),
                                avg_roas = ('ROAS','mean'),
                                min_roas = ('ROAS','min'),
                                max_profit = ('Profit_Margin','max'),
                                avg_profit = ('Profit_Margin','mean'),
                                min_profit = ('Profit_Margin','min')
                               )
                               .round(0)
                               .reset_index()
)

In [8]:
data_overview

,Subscription_Tier,Max_sales,Avg_sales,Min_sales,Max_Conversions,Avg_Conversions,Min_Conversions,Max_arpu,Mean_arpu,Min_arpu,Max_CPC,Mean_CPC,Min_CPC,max_roas,avg_roas,min_roas,max_profit,avg_profit,min_profit
0,Basic,199,102.0,1,999,504.0,1,44389.0,338.0,1.0,3714.0,34.0,0.0,184.0,5.0,0.0,98889.0,24923.0,-48938.0
1,Premium,199,100.0,1,999,501.0,1,91937.0,396.0,1.0,2426.0,30.0,0.0,135.0,5.0,0.0,96874.0,24901.0,-46821.0
2,Standard,199,100.0,1,999,492.0,1,74905.0,422.0,1.0,3904.0,32.0,0.0,149.0,5.0,0.0,96992.0,24496.0,-47459.0

In [9]:
def ROAS_range (ROAS, valoremedio = 5 , valorealto = 100):
    if ROAS <= valoremedio:
        return 'ROAS Basso'
    elif ROAS <= valorealto:
        return 'ROAS Medio'
    else :
        return 'ROAS Alto'

In [10]:
def CPC_range (Cost_per_Click, valoremedio = 34 , valorealto = 2000):
    if Cost_per_Click <= valoremedio:
        return 'CPC Basso'
    elif Cost_per_Click <= valorealto:
        return 'CPC Medio'
    else :
        return 'CPC Alto'

In [11]:
def ARPU_range (ARPU, valoremedio = 300 , valorealto = 4000):
    if ARPU <= valoremedio:
        return 'ARPU Basso'
    elif ARPU <= valorealto:
        return 'ARPU Medio'
    else :
        return 'ARPU Alto'

In [12]:
def Conversions_range (Conversions, valoremedio = 450 , valorealto = 900):
    if Conversions <= valoremedio:
        return 'Conversioni Basse'
    elif Conversions <= valorealto:
        return 'Conversioni Medie'
    else :
        return 'Conversioni Alte'

In [13]:
def Profit_range (Profit_Margin, valoremedio = 2400, valorealto = 9600):
    if Profit_Margin <= valoremedio:
        return 'Livello Profitto Basso'
    if Profit_Margin <= valorealto:
        return 'Livello Profitto Medio'
    else : 
        return 'Livello Profitto Alto'

In [14]:
# Report finale con aggiunta delle classificazioni alle variabili calcolate nel report rpecedente
campaign_report2 = (campaign_report
                    .assign(
                        Livello_ROAS = campaign_report['ROAS'].apply(ROAS_range),
                        Livello_ARPU = campaign_report['ARPU'].apply(ARPU_range),
                        Livello_Conversions = campaign_report['Total_Conversions'].apply(Conversions_range),
                        Livello_Cost_per_Click = campaign_report['Cost_per_Click'].apply(CPC_range),
                        Livello_Profitto = campaign_report['Profit_Margin'].apply(Profit_range)
                    )
                    .reset_index()
)

In [15]:
campaign_report2

,index,Campaign_ID,Subscription_Tier,Profit_Margin,ROAS,ARPU,Cost_per_Click,Units_Sold,Total_Cost,Total_Conversions,Avg_Discount_Level,ROI,Subscription_Length,Livello_ROAS,Livello_ARPU,Livello_Conversions,Livello_Cost_per_Click,Livello_Profitto
0,0,CMP_005HPN,Standard,49389.0,2.0,150.0,44.0,20,33263.0,552,59.0,3.0,23,ROAS Basso,ARPU Basso,Conversioni Medie,CPC Medio,Livello Profitto Alto
1,1,CMP_009N8Q,Basic,27702.0,2.0,117.0,66.0,52,40292.0,582,17.0,3.0,6,ROAS Basso,ARPU Basso,Conversioni Medie,CPC Medio,Livello Profitto Alto
2,2,CMP_00ASCH,Standard,53142.0,2.0,149.0,11.0,41,42099.0,640,66.0,2.0,32,ROAS Basso,ARPU Basso,Conversioni Medie,CPC Basso,Livello Profitto Alto
3,3,CMP_00QX5K,Premium,35052.0,2.0,157.0,13.0,4,49462.0,539,40.0,2.0,24,ROAS Basso,ARPU Basso,Conversioni Medie,CPC Basso,Livello Profitto Alto
4,4,CMP_00T86Z,Premium,6939.0,1.0,175.0,18.0,41,32359.0,225,64.0,4.0,17,ROAS Basso,ARPU Basso,Conversioni Basse,CPC Basso,Livello Profitto Medio
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9995,CMP_ZZBT36,Premium,2813.0,1.0,152.0,8.0,46,31526.0,226,25.0,3.0,28,ROAS Basso,ARPU Basso,Conversioni Basse,CPC Basso,Livello Profitto Medio
9996,9996,CMP_ZZIT7K,Basic,57048.0,10.0,78.0,2.0,166,6089.0,808,68.0,2.0,27,ROAS Medio,ARPU Basso,Conversioni Medie,CPC Basso,Livello Profitto Alto
9997,9997,CMP_ZZTWXP,Premium,28577.0,53.0,37.0,2.0,28,553.0,777,55.0,2.0,1,ROAS Medio,ARPU Basso,Conversioni Medie,CPC Basso,Livello Profitto Alto
9998,9998,CMP_ZZVUK1,Premium,-7393.0,1.0,23.0,9.0,80,27859.0,891,46.0,2.0,15,ROAS Basso,ARPU Basso,Conversioni Medie,CPC Basso,Livello Profitto Basso
9999,9999,CMP_ZZYX3R,Basic,64369.0,3.0,212.0,7.0,100,26588.0,429,20.0,4.0,7,ROAS Basso,ARPU Basso,Conversioni Basse,CPC Basso,Livello Profitto Alto

In [16]:
campaign_report2.to_csv('campaign_report2.csv', index=False)